apiVersion: v1
data:
  spout.properties: |
    SPRING_KAFKA_BOOTSTRAP_SERVERS=kafkaa:9092
    VIDEOSERVICE_KAFKA_SPARK_TOPIC=videoservice.topic.spark
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"videoservice-spout","creationTimestamp":null},"data":{"spout.properties":"SPRING_KAFKA_BOOTSTRAP_SERVERS=kafkaa:9092\nVIDEOSERVICE_KAFKA_SPARK_TOPIC=videoservice.topic.spark\n"}}
  creationTimestamp: 2020-01-17T16:04:34Z
  name: videoservice-spout
  namespace: default
  resourceVersion: "71"
  selfLink: /api/v1/namespaces/default/configmaps/videoservice-spout
  uid: 0dd96baa-3943-11ea-8e98-080027fd4e3d
