apiVersion: v1
data:
  spout.properties: |
    SPRING_KAFKA_BOOTSTRAP_SERVERS=PLAINTEXT://:9092
    VIDEOSERVICE_KAFKA_SPARK_TOPIC=videoservice.topic.spark
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"videoservice-spout","creationTimestamp":null},"data":{"spout.properties":"SPRING_KAFKA_BOOTSTRAP_SERVERS=PLAINTEXT://:9092\nVIDEOSERVICE_KAFKA_SPARK_TOPIC=videoservice.topic.spark\n"}}
  creationTimestamp: 2020-01-16T10:01:59Z
  name: videoservice-spout
  namespace: default
  resourceVersion: "3259"
  selfLink: /api/v1/namespaces/default/configmaps/videoservice-spout
  uid: 3ca30e26-3847-11ea-928d-080027fd4e3d
