apiVersion: v1
data:
  spout.properties: |
    SPRING_KAFKA_BOOTSTRAP_SERVERS=kafkaa:9092
    VIDEOSERVICE_KAFKA_SPARK_TOPIC=videoservice.topic.spark
    HOSTNAME=apigateway
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"videoservice-spout","creationTimestamp":null},"data":{"spout.properties":"SPRING_KAFKA_BOOTSTRAP_SERVERS=kafkaa:9092\nVIDEOSERVICE_KAFKA_SPARK_TOPIC=videoservice.topic.spark\nHOSTNAME=apigateway\n"}}
  creationTimestamp: 2020-01-19T16:11:28Z
  name: videoservice-spout
  namespace: default
  resourceVersion: "81"
  selfLink: /api/v1/namespaces/default/configmaps/videoservice-spout
  uid: 595df912-3ad6-11ea-9fdd-080027fd4e3d
