apiVersion: v1
data:
  spout.properties: |
    SPRING_KAFKA_BOOTSTRAP_SERVERS=kafkaa:9092
    VIDEOSERVICE_KAFKA_SPARK_TOPIC=videoservice.topic.spark
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"videoservice-spout","creationTimestamp":null},"data":{"spout.properties":"SPRING_KAFKA_BOOTSTRAP_SERVERS=kafkaa:9092\nVIDEOSERVICE_KAFKA_SPARK_TOPIC=videoservice.topic.spark\n"}}
  creationTimestamp: 2020-01-19T10:46:51Z
  name: videoservice-spout
  namespace: default
  resourceVersion: "236"
  selfLink: /api/v1/namespaces/default/configmaps/videoservice-spout
  uid: 005d211f-3aa9-11ea-a5e8-080027fd4e3d
