version: '3'

services:
  mysqlcontainer:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: videoservice
      MYSQL_USER: videouser
      MYSQL_PASSWORD: video
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-dev:/var/lib/mysql

  apigateway:
    image: apigateway-prod:v1
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      VIDEOSERVICE_VIDEOMANAGEMENTSERVICE: http://videomanagementservice:8090
      VIDEOSERVICE_STORAGE: file:///var/video
    volumes:
      - var:/var/video

  videomanagementservice:
    image: videomanagementservice-prod:v1
    restart: always
    links:
      - mysqlcontainer
      - videoprocessingservice
    ports:
      - "8090:8090"
    depends_on:
      - mysqlcontainer
    environment:
      SPRING_PROFILES_ACTIVE: prod
      VIDEOSERVICE_VIDEOPROCESSINGSERVICE: http://videoprocessingservice:9090/videos/process
      VIDEOSERVICE_STORAGE: /var/video
      DATABASE_TYPE: mysql
      DATABASE_HOST: mysqlcontainer
      DATABASE_PORT: 3306
      DATABASE_NAME: videoservice
      DATABASE_USER: videouser
      DATABASE_PASSWORD: video
    volumes:
      - var:/var/video

  videoprocessingservice:
    image: videoprocessingservice-prod:v1
    restart: always
    ports:
      - "9090:9090"
    environment: 
        SPRING_PROFILES_ACTIVE: prod
        VIDEOSERVICE_STORAGE: /var/video
    volumes:
      - var:/var/video
volumes:
  mysql-dev: 
  var:

