FROM maven:3-jdk-8 as builder
WORKDIR /app
COPY ["/src","/pom.xml","./"]
RUN mvn package -P production

FROM java:8
WORKDIR /app
EXPOSE 9090
ADD ./script.sh ./script.sh
COPY --from=builder /app/target/videoprocessingservice-0.0.1-SNAPSHOT.jar ./videoprocessingservice.jar
CMD java -jar videoprocessingservice.jar