FROM maven:3-jdk-8 as builder
WORKDIR /app
COPY ["/src","/pom.xml","./"]
RUN mvn package -P production

FROM java:8
WORKDIR /app
EXPOSE 8080
COPY --from=builder /app/target/apigateway-0.0.1-SNAPSHOT.jar ./apigateway.jar
CMD java -jar apigateway.jar