---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-service
---
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: mysql-service
spec:
  selector:
    matchLabels:
      app: mysql-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-service
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        envFrom:
        - configMapRef:
            name: videoservice-mysql
        - secretRef:
            name: videoservice-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
