apiVersion: v1
data:
  mysql-env.properties: |+
    MYSQL_DATABASE=videoservice

kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"videoservice-mysql","creationTimestamp":null},"data":{"mysql-env.properties":"MYSQL_DATABASE=videoservice\n\n"}}
  creationTimestamp: 2020-01-17T16:04:32Z
  name: videoservice-mysql
  namespace: default
  resourceVersion: "64"
  selfLink: /api/v1/namespaces/default/configmaps/videoservice-mysql
  uid: 0c9a41a2-3943-11ea-8e98-080027fd4e3d
