version: '3'

services:
  mysqlcontainer:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      VIDEOSERVICE_STORAGE_PATH: /var/video
      MYSQL_DATABASE: videoservice
      MYSQL_USER: videouser
      MYSQL_PASSWORD: video
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-dev:/var/lib/mysql

  apigateway:
    build:
      dockerfile: Dockerfile-dev
      context: ../apigateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      LOCALHOST_URL: http://videomanagementservice:8090
      STORAGE_URI: file:///var/video
    volumes:
      - var:/var/video

  videomanagementservice:
    build:
      dockerfile: Dockerfile-dev
      context: ../videomanagementservice
    restart: always
    links:
      - mysqlcontainer
      - videoprocessingservice
    ports:
      - "8090:8090"
    depends_on:
      - mysqlcontainer
    environment:
      VIDEOSERVICE_VIDEOPROCESSINGSERVICE: http://videoprocessingservice:9090/video/process
      VIDEOSERVICE_STORAGE: /var/video
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlcontainer:3306/videoservice?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: videouser
      SPRING_DATASOURCE_PASSWORD: video
    volumes:
      - var:/var/video

  videoprocessingservice:
    build:
      dockerfile: Dockerfile-dev
      context: ../videoprocessingservice
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - var:/var/video


volumes:
  mysql-dev: 
  var:

