FROM maven:3-jdk-8 as builder
WORKDIR /app
COPY ["/src","/pom.xml","./"]
RUN mvn package -P prod -Darguments="-DVIDEOSERVICE_STORAGE=file:///var/video -DVIDEOSERVICE_KAFKA_VMS_TOPIC=vmsTopic -DVIDEOSERVICE_KAFKA_VPS_TOPIC=vpsTopic -DVIDEOSERVICE_KAFKA=kafkaa:9092"

FROM java:8
WORKDIR /app
EXPOSE 9090
ADD ./script.sh ./script.sh
COPY --from=builder /app/target/videoprocessingservice-0.0.1-SNAPSHOT.jar ./videoprocessingservice.jar
CMD java -jar videoprocessingservice.jar
