apiVersion: v1
data:
  mysql.properties: "MYSQL_DATABASE:videoservice\r\nMYSQL_USER:videouser\r\nMYSQL_PASSWORD:video\r\nMYSQL_ROOT_PASSWORD:root"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"videoservice-mysql","creationTimestamp":null},"data":{"mysql.properties":"MYSQL_DATABASE:videoservice\r\nMYSQL_USER:videouser\r\nMYSQL_PASSWORD:video\r\nMYSQL_ROOT_PASSWORD:root"}}
  creationTimestamp: "2020-01-12T09:43:14Z"
  name: videoservice-mysql
  namespace: default
  resourceVersion: "36612"
  selfLink: /api/v1/namespaces/default/configmaps/videoservice-mysql
  uid: f41e18a8-351f-11ea-adce-00155d01061b
