---
apiVersion: v1
kind: Service
metadata:
  name: kafkaa
  labels:
    name: kafkaa
spec:
  ports:
  - port: 9092
    name: plaintext
    protocol: TCP
  selector:
    app: kafkaa
    id: "0"
  type: LoadBalancer
