apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1beta2
kind: Deployment                   
metadata:
  name: mysql 
spec:
  selector:
    matchLabels:         
      app: mysql
  template:                         
    metadata:
      labels:
        app: mysql
    spec:    
      containers:
      - name: mysql
        image: mysql:5.6           
        ports:
        - containerPort: 3306          
        volumeMounts:
        - name: mysql-persistent-storage  # This name should match the name specified in `volumes.name`
          mountPath: /var/lib/mysql
        envFrom:
            - configMapRef:
                name: videoservice-config.mysql.properties
      volumes:             
      - name: mysql-persistent-storage
        hostPath:
          path: /mnt/data
          type: DirectoryOrCreate
