FROM maven:3-jdk-8 as builder
WORKDIR /app
COPY ["/src","/pom.xml","./"]
RUN mvn package -P production

FROM java:8
WORKDIR /app
EXPOSE 8090
COPY --from=builder /app/target/videomanagementservice-0.0.1-SNAPSHOT.jar ./videomanagementservice.jar
CMD java -jar videomanagementservice.jar