apiVersion: v1
data:
  videomanagement.properties: "SPRING_PROFILES_ACTIVE:prod\nVIDEOSERVICE_VIDEOPROCESSINGSERVICE:videoprocessingservice\nVIDEOSERVICE_STORAGE:file:///var/video\nDATABASE_TYPE:mysql\nDATABASE_HOST:mysql\nDATABASE_PORT:3306\nDATABASE_NAME:videoservice\nDATABASE_USER:videouser\nDATABASE_PASSWORD:video\nVIDEOSERVICE_KAFKA_VMS_TOPIC:vmsTopic\nVIDEOSERVICE_KAFKA_VPS_TOPIC:vpsTopic\nVIDEOSERVICE_KAFKA:PLAINTEXT://:9092
    \n\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"videoservice-videomanagementservice","creationTimestamp":null},"data":{"videomanagement.properties":"SPRING_PROFILES_ACTIVE:prod\nVIDEOSERVICE_VIDEOPROCESSINGSERVICE:videoprocessingservice\nVIDEOSERVICE_STORAGE:file:///var/video\nDATABASE_TYPE:mysql\nDATABASE_HOST:mysql\nDATABASE_PORT:3306\nDATABASE_NAME:videoservice\nDATABASE_USER:videouser\nDATABASE_PASSWORD:video\nVIDEOSERVICE_KAFKA_VMS_TOPIC:vmsTopic\nVIDEOSERVICE_KAFKA_VPS_TOPIC:vpsTopic\nVIDEOSERVICE_KAFKA:PLAINTEXT://:9092 \n\n"}}
  creationTimestamp: 2020-01-16T10:01:58Z
  name: videoservice-videomanagementservice
  namespace: default
  resourceVersion: "3256"
  selfLink: /api/v1/namespaces/default/configmaps/videoservice-videomanagementservice
  uid: 3c00ba28-3847-11ea-928d-080027fd4e3d
