---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  ports:
  - port: 8080
  selector:
    app: videoservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  selector:
    matchLabels:         
      app: videoservice
  template:
    metadata:
      labels:
        app: videoservice
    spec:
      containers:
        - name: apigateway
          image: videoservice/apigateway:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          envFrom:
            - configMapRef:
                name: videoservice-apigateway
          volumeMounts:
          - mountPath: /var/video
            name: videoservice-volume
      volumes:             
      - name: videoservice-volume
        hostPath:
          path: /var
          type: DirectoryOrCreate
