---
apiVersion: v1
kind: Service
metadata:
  name: videomanagementservice
spec:
  ports:
  - port: 8090
  selector:
    app: videoservice
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: videomanagementservice
spec:
  selector:
    matchLabels:         
      app: videoservice
  template:
    metadata:
      labels:
        app: videoservice
    spec:
      containers:
        - name: videomanagementservice
          image: videoservice/videomanagementservice:latest
          imagePullPolicy: Always
          securityContext:
              privileged: true
          imagePullSecrets:
          - name: register
          ports:
          - containerPort: 8090
          envFrom:
            - configMapRef:
                name: videoservice-videomanagementservice
          volumeMounts:
          - mountPath: /var/video
            name: videoservice-volume
      volumes:             
      - name: videoservice-volume
        hostPath:
          path: /var
          type: DirectoryOrCreate
